In [1]:
from scipy.stats import ttest_rel
import numpy as np

#H0 no change in marks
#H1 change in marks

before_marks = np.array([23,3,45,23,22,6,43,22,44])
after_marks = np.array([66,76,55,88,78,98,89,88,76])

ttest_ind is for independant values 
ttest_rel is for dependant values i.e. same person ko diff marks like in the first example
ttest_1samp is for 1 sample testing

In [3]:
t_test, p_val = ttest_rel(before_marks,after_marks)
print(f'The P-value is: {p_val}')

if p_val>0.05:
    print('There cannot be any change in the marks.')
else: 
    print('There can be change in marks.')

The P-value is: 0.00015948757346193957
There can be change in marks.

In [4]:
from scipy.stats import ttest_1samp
marks = [23,3,45,23,22,6,43,22,44]
mean = np.mean(marks)

t_test, p_val = ttest_1samp(marks, 30)
print(f'P-value is: {p_val}')

if p_val>0.05:
    print('We can accept the null hypothesis.')
else: 
    print('We can reject the null hypothesis.')

P-value is: 0.42941528623133707
We can accept the null hypothesis.

In [5]:
ai1 = [23,39,45,23,22,36,43,22,44]
ai2 = [3,34,4,2,21,6,42,22,4]

In [6]:
from scipy.stats import ttest_ind
t_test, p_val = ttest_ind(ai1,ai2)
print(f'The P-value is: {p_val}')
if p_val>0.05:
    print('No diff.')
else: 
    print('There is diff.')

The P-value is: 0.010323060401878113
There is diff.

In [13]:
import pandas as pd

In [15]:
df = pd.read_excel('student-scores.xlsx')

In [17]:
df

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Larry,Waters,larry.waters.1@gslingacademy.com,male,False,2,True,24,Software Developer,80,100,92,68,83,97,60
1,2,Tracy,Payne,tracy.payne.2@gslingacademy.com,male,False,4,True,30,Pilot,86,84,70,92,68,88,75
2,3,Gregory,Hayes,gregory.hayes.3@gslingacademy.com,male,True,7,False,38,Lawyer,72,89,72,66,86,88,62
3,4,Angel,Brown,angel.brown.4@gslingacademy.com,female,True,4,True,45,Teacher,86,64,73,74,65,64,94
4,5,Ryan,Weber,ryan.weber.5@gslingacademy.com,male,False,6,False,26,Pilot,77,71,89,90,70,97,61
5,6,Benjamin,Phillips,benjamin.phillips.6@gslingacademy.com,male,False,7,True,43,Data Analyst,74,74,72,88,95,89,67
6,7,Megan,Wright,megan.wright.7@gslingacademy.com,female,False,1,False,12,Doctor,84,99,70,75,84,90,72
7,8,William,Davies,william.davies.8@gslingacademy.com,male,False,3,False,42,Pilot,74,79,99,71,83,64,86
8,9,Penny,Taylor,penny.taylor.9@gslingacademy.com,female,True,1,True,26,Journalist,60,86,74,97,73,95,60
9,10,Henry,Phillips,henry.phillips.10@gslingacademy.com,male,True,2,True,10,Lawyer,64,76,83,79,72,63,68
10,11,Christine,Steele,christine.steele.11@gslingacademy.com,female,False,2,True,20,Entrepreneur,69,86,72,64,92,93,71
11,12,Stefanie,Swanson,stefanie.swanson.12@gslingacademy.com,female,False,4,True,23,Lawyer,89,100,81,98,90,70,64
12,13,Terry,Perez,terry.perez.13@gslingacademy.com,male,True,0,True,30,Engineer,68,81,94,80,76,72,86
13,14,Taylor,Thomas,taylor.thomas.14@gslingacademy.com,female,True,1,False,28,Teacher,66,73,73,83,77,70,88
14,15,Bryan,Murphy,bryan.murphy.15@gslingacademy.com,male,False,6,True,31,Pilot,91,96,68,96,77,98,79
15,16,Mary,Campbell,mary.campbell.16@gslingacademy.com,female,False,6,False,49,Teacher,69,75,80,88,60,71,74
16,17,Guy,Turner,guy.turner.17@gslingacademy.com,male,False,3,True,26,Psychologist,86,74,97,83,98,90,65
17,18,Matthew,Blevins,matthew.blevins.18@gslingacademy.com,male,True,2,True,49,Journalist,85,97,63,80,69,81,100
18,19,Tracy,Harvey,tracy.harvey.19@gslingacademy.com,female,False,3,False,10,Doctor,88,81,73,77,90,99,70
19,20,Janet,Gill,janet.gill.20@gslingacademy.com,female,False,0,True,39,Teacher,85,64,100,98,85,70,64
20,21,Larry,Hartman,larry.hartman.21@gslingacademy.com,male,False,3,True,22,Software Developer,62,61,82,94,100,66,83
21,22,Nancy,Butler,nancy.butler.22@gslingacademy.com,female,False,2,False,50,Software Developer,87,71,75,99,92,98,76
22,23,Ricky,Underwood,ricky.underwood.23@gslingacademy.com,male,True,0,True,24,Artist,96,97,80,73,61,71,64
23,24,Andrew,Keith,andrew.keith.24@gslingacademy.com,male,True,2,False,23,Software Developer,79,80,63,98,63,75,66
24,25,Roberta,Holland,roberta.holland.25@gslingacademy.com,female,False,5,False,47,Accountant,97,98,67,95,81,62,66
25,26,Justin,Stein,justin.stein.26@gslingacademy.com,male,False,6,True,18,Accountant,61,93,64,60,89,91,81
26,27,Diana,Abbott,diana.abbott.27@gslingacademy.com,female,True,7,True,29,Software Developer,70,99,76,87,88,65,78
27,28,Jessica,Gallegos,jessica.gallegos.28@gslingacademy.com,female,False,1,True,12,Engineer,61,65,80,81,91,62,76
28,29,Ryan,Smith,ryan.smith.29@gslingacademy.com,male,True,0,False,11,Architect,87,87,82,73,94,88,82
29,30,Lori,Barnett,lori.barnett.30@gslingacademy.com,female,True,6,True,43,Pilot,89,71,77,76,72,82,66
30,31,Brianna,Little,brianna.little.31@gslingacademy.com,female,False,3,False,40,Doctor,72,94,71,66,89,86,90
31,32,Nicholas,Moore,nicholas.moore.32@gslingacademy.com,male,True,3,True,19,Psychologist,78,60,90,70,73,89,74
32,33,Gregory,Giles,gregory.giles.33@gslingacademy.com,male,True,0,True,47,Pilot,82,62,81,64,90,88,99
33,34,Melinda,Kramer,melinda.kramer.34@gslingacademy.com,female,False,3,False,34,Psychologist,68,86,93,70,100,67,85
34,35,Stephanie,Reynolds,stephanie.reynolds.35@gslingacademy.com,female,False,2,False,16,Doctor,96,76,62,79,60,93,80
35,36,Stacey,Tyler,stacey.tyler.36@gslingacademy.com,female,True,3,True,16,Data Analyst,97,69,90,62,64,96,62
36,37,Cathy,Anderson,cathy.anderson.37@gslingacademy.com,female,False,3,True,23,Entrepreneur,72,74,62,93,79,62,70
37,38,Kelly,Gibson,kelly.gibson.38@gslingacademy.com,female,True,5,True,13,Lawyer,80,98,72,99,94,94,99
38,39,Kevin,Dominguez,kevin.dominguez.39@gslingacademy.com,male,True,3,False,39,Psychologist,88,73,85,65,82,63,60
39,40,Marc,Dean,marc.dean.40@gslingacademy.com,male,False,1,False,16,Scientist,60,95,80,72,97,98,98
40,41,Candace,Saunders,candace.saunders.41@gslingacademy.com,female,True,5,False,13,Data Analyst,61,70,79,91,98,78,60
41,42,Kendra,Perez,kendra.perez.42@gslingacademy.com,female,True,1,False,14,Architect,93,62,98,66,84,99,77
42,43,Jesse,Duncan,jesse.duncan.43@gslingacademy.com,male,True,1,False,36,Teacher,99,82,65,74,73,71,61
43,44,Courtney,Hodge,courtney.hodge.44@gslingacademy.com,female,True,0,True,40,Psychologist,97,87,90,98,99,86,82
44,45,Paul,Freeman,paul.freeman.45@gslingacademy.com,male,False,3,True,30,Journalist,88,89,73,67,66,66,78
45,46,Kathleen,Howell,kathleen.howell.46@gslingacademy.com,female,True,0,True,21,Data Analyst,99,76,70,82,96,90,74
46,47,Brandon,Cohen,brandon.cohen.47@gslingacademy.com,male,False,0,True,34,Accountant,77,91,66,67,76,69,92
47,48,Tammy,Crosby,tammy.crosby.48@gslingacademy.com,female,False,1,True,37,Scientist,80,67,79,87,98,94,78
48,49,Pamela,Green,pamela.green.49@gslingacademy.com,female,False,0,True,33,Architect,90,63,94,70,79,79,91
49,50,Diane,George,diane.george.50@gslingacademy.com,female,False,2,True,40,Psychologist,81,86,74,63,96,100,70

In [23]:
print(f' The weekly self study hours is: {df['weekly_self_study_hours'].mean()}')

 The weekly self study hours is: 28.82

In [27]:
print(f'The maximum marks in math is: {df['math_score'].max()}')

The maximum marks in math is: 99

In [51]:
subjects = ['math_score','history_score','physics_score','chemistry_score','biology_score','english_score','geography_score']
ave = df[subjects[0]].mean()
for i in range(6):
    print(f'The mean are: {df[subjects[i]].mean()}')
    if df[subjects[i]].mean() < ave:
        ave = df[subjects[i]].mean()
        lowestAve = subjects[i]
print(f'The subject that requires the most effort is {lowestAve}')

The mean are: 80.0
The mean are: 80.62
The mean are: 78.3
The mean are: 79.76
The mean are: 82.34
The mean are: 81.54
The subject that requires the most effort is physics_score

In [72]:
groupA = [ 77,56,65,65,56,55,47,48,76,87]
groupB = [58,67,91,76,61,54,60,75,61,67]
t_test , p_val = ttest_ind(groupA,groupB)
print(p_val)
if p_val > 0.05:
    print('Sleep Hours Affect The Marks')
else: 
    print('Sleep Hours Do Not Affect The Marks')

0.4953802861687888
Sleep Hours Affect The Marks

In [55]:
data = np.array([
    [30, 10, 1],
    [20,30,21]
])

In [59]:
from scipy.stats import chi2_contingency

In [65]:
chi2, p, dof, expected = chi2_contingency(data)
if p > 0.05: 
    print('Gender does not affect marks')
else: 
    print('Gender affects marks')

Gender affects marks